name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
name: Set up Git user
  run:

    git config --global user.email "white.angel.3j@gmail.com"
    git config --global user.name "3b0o0oD"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci  # This ensures all packages install correctly

      - name: Set Vite Permissions (Fix for 'Permission Denied')
        run: chmod +x node_modules/.bin/vite

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
