# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows manual trigger from Actions tab
  workflow_dispatch:

# Sets GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Ensure dist Directory Exists
        run: |
          if [ ! -d "dist" ]; then
            echo "⚠️ Build failed: dist directory is missing!"
            exit 1
          fi

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Remove Old Artifacts (if any)
        run: rm -rf ./artifact || true

      - name: Upload Artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Clear GitHub Pages Cache (Fix Blank Page Issue)
        run: curl -X PURGE "https://3b0o0od.github.io/ETX/"

      - name: Verify Deployment Success
        run: 'echo "✅ Deployment completed! View it at: ${{ steps.deployment.outputs.page_url }}"'
